version: "3.5"

services:
  go-server:
    image: ghcr.io/CarlosCordoba96/lana-sre-challenge:${dockerTag}

    build:
      context: .
      dockerfile: Dockerfile
    container_name: "golang-gin-server"
    ports:
      - 8080:8080
